## Consider the below code to answer further questions:

```python
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [1]:
import numpy as np

In [3]:
list_ = ['1', '2', '3', '4', '5']

In [4]:
array_list = np.array(object = list_)

Yes, there is a difference in the data type of variables `list_` and `array_list`

In [5]:
type(list_)

list

This is the Python's general list object.

In [6]:
type(array_list)

numpy.ndarray

While this is the NumPy's array object.

## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [8]:
# data type of each element in the var `list_`
for element in list_:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Data type of each element in the list_ is string.

In [14]:
# data type of each element in the var `array_list`
print(array_list.dtype)

<U1


Data type of the elements in the array is Unicode string of length 1.

## Q3. Considering the following changes in the variable, array_list:

```python
array_list = np.array(object = list_, dtype = int)
```

Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [15]:
array_list = np.array(object = list_, dtype = int)

In [18]:
print(array_list.dtype)

int32


In [20]:
for element in list_:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


As evident by the code above, since the `dtype` parameter of the `array()` is set to "int", the data type of each element of the variable `array_list` has been changed to `int32`.  While the data type of the elements of the variable `list_` remained the same as previous i.e. string.

## Consider the below code to answer further questions:
```python
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```

## Q4. Write a code to find the following characteristics of variable, num_array:
- (i) shape
- (ii) size

In [21]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
num_array.shape

(2, 3)

The tuple says that the *first* dimension of the array `num_array` contains **2 elements** and the *second* dimension has got **3 elements**.

In [24]:
num_array.size

6

The integer represents the total number of elements in the array `num_array`, which is 6.

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [30]:
zero_arr = np.zeros(shape=(3,3))

In [31]:
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [32]:
id_matrix = np.identity(5)

In [33]:
id_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])